---
title: Migrating your workflow to R — 6 easy(ish) steps
author: Alasdair Sykes
date: '2020-08-04'
slug: migrating-your-workflow-to-r.en-us
categories:
  - R
tags:
  - R Markdown
  - RStudio
  - RShiny
  - blogdown
keywords:
  - R workflow
  - useR
---

```{r setup, include = F}
knitr::opts_chunk$set(include = T)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
```

When you look at the online portfolios of established, social-media-present R aficionados, it's tempting to assume that these folks were born authoring documents in Markdown and piecing together impossibly neat workflows to solve problems that the rest of us are too damn mundane to understand, let alone solve. I think this feeling of comparative inadequacy is particularly prevalent for the occasional useR who comes from a natural science, rather than a computational or mathematical background; most of us from this side of the tracks come to R to solve particular problems in our daily workflow (be it statistical testing, data visualisation, big data handling etc.) rather than as an intellectual exercise in and of itself.

As a result, it takes quite a bit of mental effort for us to leave aside those specific problems for long enough and actually consider making R the basis, rather than a component, of our daily workflow. I've recently made this switch, and, with the zeal of the newly enlightened, I'm now going to talk to you about it. Since going all-in on R is quite a challenging prospect for those of us who've been brought up in the comforting azure glow of the Microsoft Office suite, this blog post is basically a blow-by-blow account of the baby steps you can take in the direction of an R-based daily workflow. It's directly informed by my own journey, which means it's by no means the best, fastest or most efficient way to do things. My journey in this direction is also, I'm sure, far from complete. Nonetheless, if, like me, you're an academic with no formal programming training, but a regular 'practical' R user, I hope it might be an interesting read.

> **Before I start**. This is already shaping up to be a long-ass blog post, so I'm going to try and keep these steps as brief as possible; this is more of a **what's-possible** than a **how-to** post. It took me quite a lot of trial and error to figure out some of these steps, so I hope that by collating them all in one place, I might cut down that messing-about time for others. I'm also definitely not the best person to explain the intricacies of completing each step, so where appropriate, I'll point you in the direction of those who are. Ok --- onwards.

# 1. Start using R Markdown for everyday data analysis and communication

I came to this way, way later than I should have. Assuming you're writing R scripts to do your data analysis, there is no reason that you shoudn't or couldn't be writing .Rmd documents. It is a markdown language, so it looks and feels different to writing a document in e.g. Microsoft Word, but it's super intuitive to use, and (crucially) very easy to incorporate functional R code into. If you can write basic code in R, and you can write an email, you can write R Markdown. [This](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf) cheatsheet is really all you need to get started. Try the following:

1. Next time you have a question about an R script for a colleague/supervisor/friend, instead of copy-pasting code into the body of an email (we've all been there), try writing the question into a short, reproducible .Rmd, knit it to .html, and attach both. That way, your questionee has a well ordered, documented basis for your question, and, crucially, reproducible code.

2. If you're doing a long, complicated piece of data analysis, try using a .Rmd file as the basis, instead of a regular .R script. That way, you will be encouraged to leave a much more detailed explanation for your future self, and as a bonus, you can knit it and you'll have a pretty professional looking document to share with others who might be interested. If the code isn't reproducible (say, for example, if you have locally stored data that's read in to kick things off) it's also not the end of the world --- when you knit it locally, it's all rendered to .html, and your reader can still see what the intermediate steps and outputs look like.

# 2. Start using RStudio's *Projects* feature

I also came to this pretty late --- in fact, I only really started doing it in order to facilitate step 3 (Git), for which it's a pre-requisite. That was a mistake --- there's no single tool in RStudio which can help smooth out your workflow more than Projects. In technical terms, by creating a project in the RStudio IDE, you create a .Rproj file (and a bunch of others) in a given project directory. What this means in the real world is that, when you're working on that project, R treats the base directory of that project as your working directory. If you still start all your scripts with `setwd("some/long/ass/path/to/my/working/directory")`, you need to start using Projects. There are a number of other advantages (e.g. working on multiple projects at once, or zipping your project file and sending it to someone), but the `wd` thing is definitely the easy win here.

It's also one of the most intuitive steps in this post --- so much so that I realise I've never actually read the RStudio Projects documentation, which is [here](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects) as it turns out.

# 3. Install Git and make an account on [GitHub](https://www.github.com)

I actually did this before I started doing any of part 1, and only did part 2 in order to make this happen. In retrospect, that's topsy-turvy, but (having gone once too often for R help to the inimitable and Git-evangelical [Mike Spencer](http://mikerspencer.com)), I was persuaded of my inadequacy and, burning with shame, found the energy to get myself up and running with Git. For solo coding, the best analogy I've heard is that coding without Git (or other version control software) is like rock climbing without using protection. If (or really when) you mess up, you fall only as far as your last anchor (commit) with Git, or all the way to the ground without. And for collaborating on coding work, there really is no other way.

Version control can feel like a lot of extra effort for little gain when you start it. I think this is often because most people implement their own DIY-type version control (*script.R -> script-v2.R -> script-some-colleagues-initials.R -> script-final.R -> script-definitely-actually-final.R* --- look familiar?). Having made the move to Git, most do both initially. Once you realise the power and purpose of Git though, you can do away with the DIY stuff. It's like having all of those versions wrapped up in one, but for multiple files, annotated with reasons for the changes, and with the ability to roll back to any version at any time.

Of all the steps here, this one is probably the most valuable and, probably, has the steepest learning curve. With that said, a combination of the inbuilt GUI-accessible tools in GitHub's interface and in RStudio mean that you can get away without doing much, if anything, in the terminal --- though it's worth getting comfortable there too (I'm not especially --- yet). Of all the materials and tutorials available on the web for this step, Jenny Bryan's <https://happygitwithr.com> is the best (and best-named) that I've yet found.

# 4. Get your references into a .bib and start using it

This stopped me from using R Markdown for my entire writing workflow for the *longest* time. In retrospect, it's quite funny that the final remaining thread of my attachment to Microsoft Word was the clunky, buggy add-in from another program altogether (Mendeley Desktop, my reference manager --- if you're not using a reference manager, seriously, why aren't you using a reference manager?). It really shouldn't have surprised me that there would be a neater solution in R Markdown (or any markdown language, come to that), but it took me a Covid lockdown and a week's holiday to get around to tracking it down.

Most reference managers can create a .bib file for you --- this basically contains all of the information for all the references in your library. Mendeley even automatically updates it with new additions. Save it somewhere memorable and easily accessed, and point to it in the YAML metadata at the top of your R Markdown scripts (and optionally, do the same with a .csl file to get your desired citation style). Then use citations keys in your text (something like `@Sykes2020`), which will be rendered as proper citations, and your references section will be built automatically. Cute.

[This](https://www.rosannavanhespen.nl/2016/02/17/writing-your-thesis-with-r-markdown-2-text-citations-and-equations/) blog entry is where I started, and it's really useful, though mistaken on one point --- you don't need your *library.bib* file to be in the same folder as your .Rmd document, so long as you point to the filepath in the YAML header. A pretty comprehensive list of citation styles can be retrieved from <https://github.com/citation-style-language/styles>. I like *elsevier-harvard2.csl*, as will you if you're used to reading the usual environmental science journals.

Next time you write a report or paper manuscript, do it in R Markdown and avoid that sinking feeling when your project stakeholder or co-author asks you to change some fundamental assumption or parameter --- if you link the .Rmd directly to your analysis, it'll keep itself fully up-to-date with no more effort required.

# 5. Start building R Shiny apps

I debated whether to add this step or not, since it's more a cool addition to your workflow than anything more fundamental --- there's no real analogue for this in a non-code-based workflow. But Shiny apps are just about the best way there is to share the results of your work -- and, if you're an educator, they also make a really cool way to leverage the power of R without overburdening non-code-savvy students with the language itself. [This](https://www.github.com/aj-sykes92/msc-soil-c-modelling-tutorial) tutorial (with accompanying app) represents some of the most fun I've had teaching recently, and was well-received by students of differing R abilities. [This](https://alasdair-sykes.shinyapps.io/agroforestry-defra-prelim/) app took me a couple of days at the end of a recent project, and is currently in use by the UK government to inform GHG policy decisions.

A Shiny app can be written in a few lines of R code, and thanks to a lot of hard work by the team behind the `shiny` package, they're very intuitive to build and look like pro-level witchcraft to the uninitiated. Definitely a good level of return-on-investment for time spent learning. Get yourself a free account on <https://shinyapps.io> and anyone in the world with a web connection will be able to appreciate your genius (so long as they do so for less than 25 hours a month...). [This](https://shiny.rstudio.com/tutorial/) tutorial by Garrett Grolemund is as comprehensive an introduction as it gets, and comes with a suite of example apps.

# 6. Use R to build and manage your professional portfolio

There's no better way to convince a prospective employer of your coding chops than by making sure their introduction to your virtual self is via materials created in that coding language. I personally would put a lot more stock in reading a CV that's written in R Markdown than in reading on that CV that the applicant once took a course in R.

With that in mind, the clever folks behind the `vitae` package have made it dead easy for you to knock together a killer CV based on a .Rmd. You can even leverage other packages within it, letting you do cool stuff like use the `scholar` package to retrieve your publications from Google Scholar and use the results to build the Publications section. [This](https://cran.r-project.org/web/packages/vitae/vignettes/vitae.html) is a pretty good introduction to `vitae`.

Many folks also want to have a website these days, and it's a great way to make sure that your personal profile exists outside of your current position or institution. If you already use R Markdown (and, ideally, GitHub), the `blogdown` package, built around the Hugo framework, provides you with a simple way to build and maintain a personal website in R. This site is built with `blogdown` and Hugo's tranquilpeak template (find it [here](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/docs/user.md)). The site is essentially a GitHub repository that deploys directly the the domain via [Netlify](https://www.netlify.com). Blog posts are super easy to write in the RStudio IDE, and I have all of the advantages that come with writing in R Markdown and managing version control with Git.

# That's all folks

Hopefully that gives anyone who's thinking of going cold-turkey on the MS Office-based workflow a few places to start. I'm by no means an expert and am definitely still fumbling my way through it; for example, I've yet to explore the `bookdown` package for writing more complex documents with Markdown, so I'm looking forward to giving that a try. I always have the impression when I'm reading instructionals on this stuff that the writer got it all right first time, so I've tried --- hopefully with some success --- to avoid that here. Let me know if you have anything you'd add to this list, or anything you'd change. Cheers!

